### ISSUE TITLE
Internal Server Error The server has either erred or is incapable of performing the requested operation.

### ISSUE THREAD

**Issue by city535353** [GoogleCloudPlatform/appengine-guestbook-python#40] opened 2018-05-06 23:55 UTC
When I upload to GAE, and test it with URL. The error is:
NeedIndexError: no matching index found. recommended index is:
- kind: Greeting
  ancestor: yes
  properties:
  - name: date
    direction: desc

The suggested index for this query is:
- kind: Greeting
  ancestor: yes
  properties:
  - name: date
    direction: desc

**Comment by narenchoudhary** [comment] 2018-08-17 18:26
This issue seems to be a duplicate of #38 .

**Comment by flik** [comment] 2018-12-23 11:46
same issue with me and fixed with : gcloud app deploy app.yaml 
It should be update in google document https://cloud.google.com/shell/docs/quickstart

**Comment by meredithslota** [comment] 2022-07-26 16:33
https://cloud.google.com/shell/docs/deploy-app-engine-app has been updated.

**Closed by meredithslota** 2022-07-26 16:33 UTC
